### ISSUE TITLE
Clarify expiry rounding in the spec

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#923] opened 2023-07-31 17:50 UTC
In step 20 of https://wicg.github.io/attribution-reporting-api/#parse-source-registration-json, source event expiries get rounded to the nearest day. It is not clear why this is being done, we should provide a non-normative note explaining this.

**Comment by apasel422** [comment] 2023-08-01 13:02
Duplicate of #908

**Closed by apasel422** 2023-08-01 13:02 UTC
Labels: documentation
