### ISSUE TITLE
Detecting Invalid Traffic with Attribution and Aggregate Reporting

### ISSUE THREAD

**Issue by SpaceGnome** [WICG/attribution-reporting-api#223] opened 2021-09-16 18:51 UTC
Detecting invalid traffic (IVT) is an essential part of the ads ecosystem and often relies on: 

- Human Analysis for manual investigations, discovering new attacks and developing new IVT models 
- Training and deploying Automated IVT detection models

However, the use of aggregated reporting within [Attribution Reporting API with Aggregate Reports](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md) makes the above IVT use cases challenging. We’ve written up a proposal called [ASTRAPIA](https://github.com/google/ads-privacy/tree/master/proposals/astrapia) to address these key IVT detection use cases (although the ASTRAPIA proposal is currently written for FLEDGE, it could also be generalized for Attribution Reporting with Aggregate Reporting too).

We look forward to further discussing ASTRAPIA or other ideas for supporting Attribution Reporting and IVT detection either here or as an issue in https://github.com/google/ads-privacy/issues. Thanks!

**Comment by csharrison** [comment] 2021-11-15 00:28
Hey @SpaceGnome would you like to present this topic in a future WICG call?

**Comment by SpaceGnome** [comment] 2021-11-15 19:14
Thanks @csharrison  - let me plan to add this to the agenda for December.

**Comment by csharrison** [comment] 2021-11-29 21:38
I added this to the agenda for our next meeting on Dec 13. Can you make it?

**Comment by SpaceGnome** [comment] 2021-11-29 23:06
Yes, that sounds great @csharrison!

**Comment by Abdullah9aleh** [comment] 2021-12-20 14:18
> Detecting invalid traffic (IVT) is an essential part of the ads ecosystem and often relies on:
> 
> * Human Analysis for manual investigations, discovering new attacks and developing new IVT models
> * Training and deploying Automated IVT detection models
> 
> However, the use of aggregated reporting within [Attribution Reporting API with Aggregate Reports](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md) makes the above IVT use cases challenging. We’ve written up a proposal called [ASTRAPIA](https://github.com/google/ads-privacy/tree/master/proposals/astrapia) to address these key IVT detection use cases (although the ASTRAPIA proposal is currently written for FLEDGE, it could also be generalized for Attribution Reporting with Aggregate Reporting too).
> 
> We look forward to further discussing ASTRAPIA or other ideas for supporting Attribution Reporting and IVT detection either here or as an issue in https://github.com/google/ads-privacy/issues. Thanks!

Duplicate of #

**Comment by csharrison** [comment] 2023-04-13 20:20
Closing for now as we don't have current plans to integrate this proposal. Note that we recently published https://github.com/WICG/attribution-reporting-api/blob/main/report_verification.md to partially satisfy the IVT use-case.

**Closed by csharrison** 2023-04-13 20:20 UTC
Labels: anti-fraud / auth
