### ISSUE TITLE
Flexible event phase 2

### ISSUE THREAD

**Issue by arielhal** [WICG/attribution-reporting-api#1090] opened 2023-10-31 13:31 UTC
Hey @csharrison !
Is there an estimation for when Phase 2 (Full Flexible Event-Level) will be available?
https://github.com/WICG/attribution-reporting-api/blob/main/flexible_event_config.md#phase-2-full-flexible-event-level
Thanks!

**Comment by apasel422** [comment] 2023-10-31 15:23
Duplicate of https://github.com/WICG/attribution-reporting-api/issues/733#issuecomment-1787252483.

**Closed by apasel422** 2023-10-31 15:23 UTC
